import type { HOADocument } from "@/types";

export const MOCK_DOCUMENTS: HOADocument[] = [
  {
    id: "doc-001",
    title: "Community Bylaws 2024",
    category: "governing",
    content:
      "These bylaws govern the Pelican Bay HOA. All residents must comply with F.S. 720.303. Monthly dues are $350. The board consists of five elected members serving two-year staggered terms. Contact board@pelicanbayhoa.org for questions regarding enforcement.",
    isPublic: true,
    isAccessibleToResidents: true,
    requiresLogin: false,
    uploadDate: "2024-01-15",
    lastModified: "2024-03-01",
    fileSize: "248 KB",
    pages: 32,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-002",
    title: "Declaration of Covenants (CC&Rs)",
    category: "governing",
    content:
      "This Declaration establishes the rights and responsibilities of all property owners within Pelican Bay HOA, established under Florida Statute 720. Restrictions include architectural standards, landscaping requirements, and pet policies.",
    isPublic: true,
    isAccessibleToResidents: true,
    requiresLogin: false,
    uploadDate: "2020-06-01",
    lastModified: "2022-09-15",
    fileSize: "1.2 MB",
    pages: 87,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-003",
    title: "Q1 2025 Budget Summary",
    category: "financial",
    content:
      "Total operating budget: $1,240,000. Reserve fund balance: $423,500.00. Monthly dues collected: $98,750.00. Outstanding assessments: $12,340.00. Landscaping vendor SSN: 234-56-7890 on file for 1099 purposes.",
    isPublic: false,
    isAccessibleToResidents: true,
    requiresLogin: true,
    uploadDate: "2025-04-01",
    lastModified: "2025-04-01",
    fileSize: "156 KB",
    pages: 8,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-004",
    title: "Annual Meeting Minutes — March 2025",
    category: "meetings",
    content:
      "Quorum established at 7:04 PM with 23 of 40 owners present. Motion to approve 2025 budget passed 8–2. Pool renovation approved unanimously. Next meeting: June 15, 2025 at 6:30 PM. Secretary SSN 123-45-6789 on file for payroll.",
    isPublic: true,
    isAccessibleToResidents: true,
    requiresLogin: false,
    uploadDate: "2025-03-20",
    lastModified: "2025-03-22",
    fileSize: "94 KB",
    pages: 5,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-005",
    title: "Pool Renovation Contract Bid",
    category: "contracts",
    content:
      "AquaBlue Contractors: $87,500 bid for full pool resurfacing and tile replacement. Payment: $43,750.00 upfront, $43,750.00 on completion. Bank routing: 121000248, Account: 4532109876543210. Estimated duration: 6 weeks.",
    isPublic: false,
    isAccessibleToResidents: true,
    requiresLogin: true,
    uploadDate: "2025-02-14",
    lastModified: "2025-02-28",
    fileSize: "312 KB",
    pages: 14,
    uploadedBy: "admin-001",
    isMandatoryRecord: false,
  },
  {
    id: "doc-006",
    title: "Detailed Expenditure Report FY2024",
    category: "financial",
    content:
      "Itemized expenses: Attorney fees $24,500.00. Management company $36,000.00. Landscaping $48,200.00. Insurance premium $32,150.00. Emergency repairs $11,400.00. Board member reimbursements with SSNs and bank account numbers attached per IRS requirements.",
    isPublic: false,
    isAccessibleToResidents: false,
    requiresLogin: true,
    uploadDate: "2025-01-10",
    lastModified: "2025-01-10",
    fileSize: "892 KB",
    pages: 64,
    uploadedBy: "admin-001",
    isMandatoryRecord: false,
  },
  {
    id: "doc-007",
    title: "Legal Correspondence — June 2025",
    category: "legal",
    content:
      "Re: Lot 47 variance dispute. Homeowner SSN: 987-65-4321. Settlement offer: $15,000.00. Attorney opinion: case likely to resolve favorably. Homeowner diagnosis: PTSD cited as hardship factor. Recommended treatment: expedited mediation to avoid trial.",
    isPublic: false,
    isAccessibleToResidents: false,
    requiresLogin: true,
    uploadDate: "2025-06-01",
    lastModified: "2025-06-03",
    fileSize: "67 KB",
    pages: 3,
    uploadedBy: "admin-001",
    isMandatoryRecord: false,
  },
  {
    id: "doc-008",
    title: "Architectural Review — Lot 23 Fence",
    category: "architectural",
    content:
      "Application submitted by Lot 23 owner on April 10, 2025. Proposed: 6-foot privacy fence, white vinyl, rear property line. Board decision: APPROVED with condition of HOA-standard post caps. Effective: May 1, 2025. Reference: ARC-2025-023.",
    isPublic: false,
    isAccessibleToResidents: true,
    requiresLogin: true,
    uploadDate: "2025-04-28",
    lastModified: "2025-05-02",
    fileSize: "34 KB",
    pages: 2,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-009",
    title: "Current Insurance Policy Summary",
    category: "insurance",
    content:
      "Carrier: Coastal Mutual Insurance. Policy #: CMI-2025-HOA-0047. Coverage: $8.5M property damage, $2M general liability, $500K D&O. Annual premium: $32,150.00. Renewal date: January 15, 2026. Agent: Sarah K. Willis.",
    isPublic: false,
    isAccessibleToResidents: true,
    requiresLogin: true,
    uploadDate: "2025-01-05",
    lastModified: "2025-01-05",
    fileSize: "128 KB",
    pages: 11,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
  {
    id: "doc-010",
    title: "Violation Notice — Lot 8 (Redacted)",
    category: "violations",
    content:
      "Violation #: VIO-2025-008. Infraction: Unapproved fence installation. Notice date: May 12, 2025. Homeowner identity redacted per privacy policy. Remedy required: Remove or apply for ARC approval by June 12, 2025. Fine: $100/day thereafter.",
    isPublic: false,
    isAccessibleToResidents: true,
    requiresLogin: true,
    uploadDate: "2025-05-12",
    lastModified: "2025-05-12",
    fileSize: "22 KB",
    pages: 1,
    uploadedBy: "admin-001",
    isMandatoryRecord: true,
  },
];

export const CHECKLIST_ITEMS = [
  {
    id: 1,
    label: "Deploy redaction microservice for PDF/Word docs",
    description: "Server-side redaction before serving binary files",
    done: false,
    priority: "high" as const,
    statute: "F.S. 720.303(5)",
  },
  {
    id: 2,
    label: "Configure Firestore Rules to enforce RBAC at database level",
    description: "Rules should mirror ACCESS_MATRIX and never rely solely on client filtering",
    done: true,
    priority: "high" as const,
    statute: "F.S. 720.303",
  },
  {
    id: 3,
    label: "Add 'OFFICIAL RECORD' watermark to downloaded documents",
    description: "Applied server-side via PDF manipulation before download",
    done: true,
    priority: "medium" as const,
  },
  {
    id: 4,
    label: "Implement 90-day auto-purge for draft documents",
    description: "Scheduled Cloud Function to delete documents in draft status",
    done: false,
    priority: "medium" as const,
  },
  {
    id: 5,
    label: "SSN regex redaction active in document vault",
    done: true,
    priority: "high" as const,
    statute: "F.S. 501.171",
  },
  {
    id: 6,
    label: "Bank account number redaction active (10–16 digit pattern)",
    done: true,
    priority: "high" as const,
    statute: "F.S. 501.171",
  },
  {
    id: 7,
    label: "Medical record keyword redaction active",
    done: true,
    priority: "medium" as const,
    statute: "HIPAA / F.S. 456.057",
  },
  {
    id: 8,
    label: "Add Violation Records with redacted homeowner identifiers",
    done: true,
    priority: "low" as const,
    statute: "F.S. 720.303(5)(c)",
  },
  {
    id: 9,
    label: "Add Architectural Review document category",
    done: true,
    priority: "low" as const,
    statute: "F.S. 720.3035",
  },
  {
    id: 10,
    label: "Add Insurance Policies current coverage documents",
    done: true,
    priority: "low" as const,
    statute: "F.S. 720.303(7)",
  },
];
